<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="ClosedXML" Version="0.104.2" />
		<PackageReference Include="DeepCloner" Version="0.10.4" />
		<PackageReference Include="Extensions.Converters" Version="1.0.0" />
		<PackageReference Include="Extensions.Generator" Version="1.0.0" />
		<PackageReference Include="Extensions.Password" Version="1.0.0" />
		<PackageReference Include="FirebaseAdmin" Version="3.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.7.0" />
		<PackageReference Include="GoogleAuthenticator" Version="3.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\URLS.Constants\URLS.Constants.csproj" />
		<ProjectReference Include="..\URLS.Domain\URLS.Domain.csproj" />
		<ProjectReference Include="..\URLS.Infrastructure.Data\URLS.Infrastructure.Data.csproj" />
	</ItemGroup>

</Project>
